## Task configurations
help_patients:
  description: |
    Analyze the blood test report at: {file_path} to address the user's query: {query}

    Provide a detailed interpretation of any abnormal blood values and explain their clinical significance.
    Identify patterns that may indicate potential health concerns.
    Explain normal ranges and what they mean in plain language.
    Prioritize important findings that require attention.

    If relevant to the query, suggest follow-up actions like additional tests or medical consultations.
    Provide evidence-based recommendations and avoid alarming the patient unnecessarily.
    Use proper medical terminology but explain concepts in patient-friendly language.

    Your analysis should be comprehensive but focused on addressing the specific query.
  expected_output: |
    A detailed, evidence-based interpretation of the blood test results addressing the user's query.

    Include:
    1. A summary of key findings in the blood test
    2. Explanation of any abnormal values and their potential significance
    3. Context for understanding the results (normal ranges, what tests measure)
    4. Evidence-based recommendations for follow-up if needed
    5. Clear explanations that balance medical accuracy with patient-friendly language

    The analysis should be professional, reassuring where appropriate, and clearly indicate when medical follow-up is necessary.

nutrition_analysis:
  description: |
    Based on the blood test report at: {file_path}, provide personalized nutritional recommendations.

    Focus specifically on addressing nutritional factors related to the user's query: {query}
    Identify blood markers that have nutritional implications (e.g., iron, vitamin levels, cholesterol).
    Suggest specific dietary changes that could help improve abnormal values.
    Provide practical, evidence-based nutritional advice tailored to the blood test results.

    Include recommendations for:
    - Specific foods to include or limit
    - Meal timing and frequency if relevant
    - Potential nutrient deficiencies indicated by the results
    - Dietary patterns supported by current nutritional science

    Avoid recommending supplements unless clearly indicated by significant deficiencies.
    Focus on whole-food approaches when possible.
  expected_output: |
    A comprehensive nutritional analysis based on the blood test results, including:

    1. Identification of key nutritional markers from the blood test
    2. Evidence-based dietary recommendations to address any imbalances
    3. Specific foods and dietary patterns that may help improve health markers
    4. Practical implementation strategies (meal suggestions, food substitutions)
    5. Clear explanation of how the recommended nutritional changes may impact blood values

    The recommendations should be practical, sustainable, and tailored to the specific blood test results.

exercise_planning:
  description: |
    Create a personalized exercise plan based on the blood test report at: {file_path} and the user's query: {query}

    Consider how specific blood markers might impact exercise tolerance and recommendations.
    Develop appropriate exercise recommendations that account for any health considerations.
    Include guidance on exercise type, frequency, intensity, and duration.
    Provide modifications based on any limitations indicated by blood values.

    Focus on:
    - Safe and appropriate exercise progressions
    - Types of exercise that may help improve abnormal values
    - Precautions based on any concerning blood markers
    - Monitoring parameters during exercise if relevant

    Ensure all recommendations follow clinical exercise guidelines and account for safety.
  expected_output: |
    A personalized exercise plan based on blood test results, including:

    1. Assessment of how blood markers may impact exercise tolerance and safety
    2. Specific exercise recommendations (type, frequency, intensity, duration)
    3. Progressive plan that accounts for current health status
    4. Safety precautions and modifications if needed
    5. Guidance on monitoring response to exercise

    The plan should be evidence-based, realistic, and account for any limitations indicated by the blood test results.

verification:
  description: |
    Carefully review the analysis provided by the other specialists to verify accuracy and completeness.

    Confirm that the blood test report at: {file_path} has been correctly interpreted.
    Verify that all recommendations are evidence-based and medically sound.
    Check for any potential inconsistencies or misinterpretations in the previous analyses.
    Ensure all important abnormal values have been addressed appropriately.

    Your role is to act as a final quality check before delivering recommendations to the user.
    Focus on accuracy, completeness, and ensuring recommendations align with current medical guidelines.
  expected_output: |
    A verification report that includes:

    1. Confirmation of accurate interpretation of blood test results
    2. Validation of the recommendations provided by other specialists
    3. Corrections or clarifications for any potential misinterpretations
    4. Identification of any important information that may have been overlooked
    5. A final integrated assessment that confirms the validity of the overall analysis

    The verification should ensure all information provided is medically accurate, evidence-based, and addresses the user's query comprehensively.
